### PR TITLE
Fix for JENKINS-55715

### PR DESCRIPTION
**Pull request by jftsunami**
Makes educated guesses at the file names for TagList

### CODE REVIEW

**Comment by uhafner** [comment]
Wouldn't it make more sense if this change is part of the analysis-model library? There you could also map the package name, so no post processing is required.

**Comment by jftsunami** [comment]
Answer depends on the scope of the analysis-model library, is it supposed to represent the data in the parsed files verbatim, or perform transformations like class name to file? I started the modification in analysis-model, but then moved it over here if the answer is 'Yes the library should report what is in the parsed file', but I can move it easily enough back into the library if you so desire.

**Comment by jftsunami** [comment]
You can close this and take PR #81 in analysis-model as the alternative.

**Comment by uhafner** [comment]
Replaced by https://github.com/jenkinsci/analysis-model/pull/81.

**Pull request closed without merging**
