### PR TITLE
Pick up `forkCount` fix from `acceptance-test-harness`

### PR DESCRIPTION
**Pull request by jglick**
Follows up #1327 by picking up https://github.com/jenkinsci/acceptance-test-harness/pull/885. Would appreciate a release. @basil @uhafner

### CODE REVIEW

**Comment by uhafner** [comment]
How does a release of the warnings plugin help here? A release currently is executed in the `plugin` folder only. The UI tests are not affected by a release up to now. Or how do you use the UI tests together with the plugin in your PCT? Wouldn't it make more sense to simply ignore the UI tests in PCT?

**Comment by jglick** [comment]
Currently the UI tests do seem to get run in PCT. Perhaps it would make sense to ignore them, but I would need to explore how to do that. At any rate, it seems worth a shot at having them just pass.

**Comment by jglick** [comment]
> How does a release of the warnings plugin help here?

Simply by having a different release tag. PCT checks out plugin sources from the version tag before running tests.

**Review by uhafner — APPROVED** [review]

**Comment by uhafner** [comment]
Release is in progress...

**Comment by jglick** [comment]
https://github.com/jenkinsci/acceptance-test-harness/pull/885#issuecomment-1212132140 I guess this was merged without CI passing?

**Comment by uhafner** [comment]
Yes, I thought it is urgent to get the release out. Since there were no changes in the plugin I thought that it was safe. Since GitHub actions sometimes have problems when accessing Jenkins resources I thought it would not harm.

**Comment by jglick** [comment]
https://github.com/jenkinsci/acceptance-test-harness/pull/885#issuecomment-1212192991 try again

**Comment by uhafner** [comment]
https://github.com/jenkinsci/warnings-ng-plugin/releases/tag/v9.17.0

**Pull request merged**
