### PR TITLE
Add Pylint icons

### PR DESCRIPTION
**Pull request by JeanChristopheMorinPerso**
Simply adding Pylint icons.

Changes in the supported formats file were generated by ToolsLister, as it should. It took me some time to figure out how to run it. Should we document how to run it?

### CODE REVIEW

**Comment by uhafner** [comment]
Thanks! What is the license for the icons? Maybe we can add it to the License.txt file.

**Comment by uhafner** [comment]
Where would be a good place to document the ToolsLister? I added a reference in the first line of the generated report, seems that this is not sufficient?

**Comment by JeanChristopheMorinPerso** [comment]
@uhafner Pylint is licensed under GNU General Public License v2.0 (https://github.com/PyCQA/pylint/blob/master/COPYING). The logo can be found at https://github.com/PyCQA/pylint/blob/master/doc/logo.png in the Pylint repo.

As for the ToolsLister, I can tell you that for me it wasn't obvious where that tool was in the first place, and then I had difficulties to understand why it wasn't executed with the tests (after I found that it was in the tests folder). Could it potentially be a maven goal or something just so we don't have to modify the pom.xml file to include the file in the test run ? (I'm far from a Java developer, so maybe it's not possible). For me, the end goal would be to make it even more easy for people that wants to contribute and that doesn't know the Java development stack that well (like me for example). What do you think?

**Comment by uhafner** [comment]
Hmm, I think we can't include something that is under GPL. IANAL but as far as I understand the license it is viral, i.e. I need to publish under GPL as well, I'm not sure how this is still valid by using the icon only.

**Comment by douardda** [comment]
Hi, I am the author of this icon. It's a quick'n dirty small icon I made (and I am in no way a designer of any kind, obviously) a while ago when I was at Logilab (my former employer and creator of pylint).

Not sure what I can do about this, but I'll see if the logo can be relicensed.

**Comment by uhafner** [comment]
IANAL but if you are the author of the icon I think we can add a copyright from you into the license.txt file. But if you could check with Logilab it would be more save...

**Comment by douardda** [comment]
well, the project is now managed by the community, so I think a PR on pylint's project should be ok. But I'll catch Logilab as well.

**Comment by uhafner** [comment]
Ah, then it might be sufficient to ask in the project...

**Comment by JeanChristopheMorinPerso** [comment]
Thanks @douardda for jumping in. Earlier, I tried to contact the PyCQA (Python Code Quality Authority) mailing list (see https://mail.python.org/pipermail/code-quality/2019-February/001097.html) but got no answer. I guess I should have asked straight in the GitHub repo...

**Comment by JeanChristopheMorinPerso** [comment]
@uhafner Good news is that the icon was re-licensed and the license change has been merged in pylint master. I guess we can proceed at adding the license in this repo.

Thanks @douardda :)

**Pull request merged**
