### PR TITLE
Add support for IBLinter (Swift storyboard linter)

### PR DESCRIPTION
**Pull request by nysander**

### CODE REVIEW

**Comment by nysander** [comment]
why Jenkins build is not done after 8h?

**Comment by uhafner** [comment]
Can you please create a small test in [ParsersITest](https://github.com/jenkinsci/warnings-ng-plugin/blob/master/src/test/java/io/jenkins/plugins/analysis/warnings/ParsersITest.java#L70)?

**Comment by nysander** [comment]
I'm afraid not. I do not have any knowledge about Java and IBLinter module which I want to integrate with this plugin. I just copied and updated files from other module which uses the same Checkstyle reporter (SwiftLint). I can provide updated changelog.

**Comment by uhafner** [comment]
Ok, never mind, I can add it later on, the test is just one simple line: https://github.com/jenkinsci/warnings-ng-plugin/blob/master/src/test/java/io/jenkins/plugins/analysis/warnings/ParsersITest.java#L70

Can you provide a small report xml with one warning from your tool? Then I can use it for the test.

**Comment by nysander** [comment]
Here is output from IBLinter:

[test.xml.zip](https://github.com/jenkinsci/warnings-ng-plugin/files/3038116/test.xml.zip)

**Comment by nysander** [comment]
here is XML file generated by IBLinter
[test.xml.zip](https://github.com/jenkinsci/warnings-ng-plugin/files/3038139/test.xml.zip)

**Comment by nysander** [comment]
thank you

**Comment by uhafner** [comment]
Well, thank you!

**Comment by nysander** [comment]
@uhafner do you have any date when you plan to release this PR?

**Pull request merged**
