### PR TITLE
Updating Ansible Icon license details 

### PR DESCRIPTION
**Pull request by rahuldimri**
#1392 
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by uhafner** [comment]
Can you please provide *one* PR with the logo and the license?

**Comment by rahuldimri** [comment]
Going forward I will take care of this; I was trying to open to create ate single PR but somehow not able to do that. Still if you feel I need to open single PR will try.

**Review by uhafner — CHANGES_REQUESTED** [review]

**Comment by uhafner** [comment]
And please make sure that the icon actually is shown in the UI. You need:

- use `SvgIconLabelProvider`
- recreate the file https://github.com/jenkinsci/warnings-ng-plugin/blob/master/SUPPORTED-FORMATS.md

**Comment by rahuldimri** [comment]
Once this file uploaded successfully, Will make it available in front end.

**Pull request closed without merging**
