### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by uhafner**
Remove all deprecated methods and fields.

Based on #1649.

### CODE REVIEW

**Comment by sach-edna** [comment]
Hi, thanks for documenting these changes. Please excuse my ignorance of this information, but is there some place these changes are documented beforehand or for the future? 

We use the warnings-ng plugin for taskscanner, parasoft, pylint, iar, gcc, cmaken, mypy in about 50 pipeline projects. When updating the warnings-ng plugin we got an syntax error across most of our pipelines. Is there some way we could have known this was coming (except monitoring the PR's and commits in this repo)? 

Since we will have to update most of our pipelines, it would be nice if we could have an idea which breaking syntax changes are coming, to plan our maintenance accordingly.

Thanks for your hard work in maintaining this plugin!

**Comment by uhafner** [comment]
> Hi, thanks for documenting these changes. Please excuse my ignorance of this information, but is there some place these changes are documented beforehand or for the future?
> 
> We use the warnings-ng plugin for taskscanner, parasoft, pylint, iar, gcc, cmaken, mypy in about 50 pipeline projects. When updating the warnings-ng plugin we got an syntax error across most of our pipelines. Is there some way we could have known this was coming (except monitoring the PR's and commits in this repo)?
> 
> Since we will have to update most of our pipelines, it would be nice if we could have an idea which breaking syntax changes are coming, to plan our maintenance accordingly.
> 
> Thanks for your hard work in maintaining this plugin!

The required changes are typically part of the release notes (https://github.com/jenkinsci/warnings-ng-plugin/releases/tag/v11.0.0) or the pull request. Most removed attributes have been marked as deprecated for quite a while.  So it makes sense to check these before doing a major version upgrade.

For some of the properties it wasn't possible to leave the property in place as I moved the functionality to a different plugin.

**Comment by sach-edna** [comment]
Thanks for this information. We will keep in mind to check the release notes for further changes. Do you have a plan/roadmap for future syntax changes? Since we have to update quite a few of them it would be helpful to know is new changes will be coming soon. If not we will update to the new syntax, otherwise we will wait a bit until the new syntax is added.


Met vriendelijke groeten, Meilleures salutations,
Kind regards, Mit freundlichen Grüßen,

Peter Sacharias
Embedded Software Engineer

Visit us at MCE2024 (12.03-15.03 Fiera Milano, Italy). Order your free entrance code here.<https://www.edna.eu/en/news-item/e-d-a-is-exhibiting-at-mce-2024-it-order-your-free-admission-voucher-20240211>


[cid:logo_edna_0a53b7c0-b1a7-4767-a3a5-fdab17d03292.jpg]
***@***.***>


E.D.&A. nv  Franseweg 20, 2920 Kalmthout, Belgium
E-mail ***@***.******@***.***>
Phone +32 3 620 18 18  Extension 177
Internet http://www.edna.eu/<https://www.edna.eu/>
VAT BE 0459.777.129  RPR Antwerp
        [cid:FotF_2022_da7e3ef7-48ea-4e59-88c2-66e99d8cc48d.jpg] <https://www.edna.eu/en/production/factory-of-the-future>

All our commercial relations are subjected to our general sales terms<https://www.edna.eu/salesconditions> and general purchasing conditions<https://www.edna.eu/purchaseconditions>.




[cid:banner_mostra_email_97c52daf-3525-40c0-90a7-ccda23880102.jpg]<https://www.edna.eu/en/news-item/e-d-a-is-exhibiting-at-mce-2024-it-order-your-free-admission-voucher-20240211>
Van: Ullrich Hafner ***@***.***>
Verzonden: woensdag 13 maart 2024 10:22
Aan: jenkinsci/warnings-ng-plugin ***@***.***>
CC: Peter Sacharias ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [jenkinsci/warnings-ng-plugin] Remove deprecated code (PR #1652)


Hi, thanks for documenting these changes. Please excuse my ignorance of this information, but is there some place these changes are documented beforehand or for the future?

We use the warnings-ng plugin for taskscanner, parasoft, pylint, iar, gcc, cmaken, mypy in about 50 pipeline projects. When updating the warnings-ng plugin we got an syntax error across most of our pipelines. Is there some way we could have known this was coming (except monitoring the PR's and commits in this repo)?

Since we will have to update most of our pipelines, it would be nice if we could have an idea which breaking syntax changes are coming, to plan our maintenance accordingly.

Thanks for your hard work in maintaining this plugin!

The required changes are typically part of the release notes (https://github.com/jenkinsci/warnings-ng-plugin/releases/tag/v11.0.0<https://github.com/jenkinsci/warnings-ng-plugin/releases/tag/v11.0.0>) or the pull request. Most removed attributes have been marked as deprecated for quite a while. So it makes sense to check these before doing a major version upgrade.

For some of the properties it wasn't possible to leave the property in place as I moved the functionality to a different plugin.

**Comment by uhafner** [comment]
> Thanks for this information. We will keep in mind to check the release notes for further changes. Do you have a plan/roadmap for future syntax changes? Since we have to update quite a few of them it would be helpful to know is new changes will be coming soon. If not we will update to the new syntax, otherwise we will wait a bit until the new syntax is added. 

There are no major upgrades planned in the near future since my research semester is finished I am back to my normal schedule which doesn't allow to make bigger changes...

**Comment by sunnypatel2141** [comment]
Hi
Why was referenceJobName deleted? Is there an alternate to this >

**Comment by uhafner** [comment]
Yes, you need to use the reference recorder step. See forensics api plugin.

**Comment by sunnypatel2141** [comment]
Thanks.
Can you tell how we can convert
```
           recordIssues qualityGates: [
             [threshold: 1, type: 'TOTAL_HIGH', unstable: true], 
             [threshold: 1, type: 'TOTAL_NORMAL', unstable: true], 
             [threshold: 1, type: 'TOTAL_LOW', unstable: true], 
             [threshold: 6, type: 'TOTAL_HIGH', unstable: false], 
             [threshold: 6, type: 'TOTAL_NORMAL', unstable: false], 
             [threshold: 6, type: 'TOTAL_LOW', unstable: false]
             ], 
             referenceJobName: '/Lego/lego-pipeline/build/lego-multibranch/master',
             tools: [findBugs(pattern: '**/reports/spotbugs/*.xml', useRankAsPriority: true)]
```

This to use two plugins now ? recordIssues + discoverReferenceBuild. An example would really help. Thanks.

**Comment by uhafner** [comment]
See https://github.com/jenkinsci/warnings-ng-plugin/blob/main/doc/Documentation.md#configure-the-selection-of-the-reference-build-baseline

**Comment by maciejmatczak** [comment]
Hello. Got here by a long journey - from failing pipelines. Disappearing `ignoreFailedBuilds` brought me here. Docs of 11.10.0 still mentions it as a go-to solution: https://github.com/search?q=repo%3Ajenkinsci%2Fwarnings-ng-plugin%20ignoreFailedBuilds&type=code.

It's hard to me to realize what's the proper migration flow after this deprecation, any help appreciated.

**Pull request merged**
