### PR TITLE
Add icon file for Ansible

### PR DESCRIPTION
**Pull request by rahuldimri**
We don't have ansible icon, which is causing page to fail. 
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by uhafner — COMMENTED** [review]
Thanks for your PR!
- Is there no SVG image available? 
- Is there an image available that just contains the A (without the text), this would be better readable in the actions
- You need to add licensing information in https://github.com/jenkinsci/warnings-ng-plugin/blob/master/plugin/src/main/webapp/icons/LICENSE.txt
-

**Comment by rahuldimri** [comment]
ok let me close this one and open the new one.

**Comment by rahuldimri** [comment]
@uhafner could you please approve this request.

**Comment by uhafner** [comment]
I'm not sure what your plan is with the two pull requests. 

It would make sense to have **one** PR that contains:

- the SVG icon (and no PNG icon)
- the license changes
- the correct reference in the icon provider
- the updated SUPPORTED-FORMATS file

As the Ansible icon is black and white: you can even try to create a symbol, see: https://weekly.ci.jenkins.io/design-library/Symbols/. Then it will be automatically adapted on the dark theme.

**Pull request closed without merging**
