### PR TITLE
Add `pluginRepositories` for PCT

### PR DESCRIPTION
**Pull request by basil**
My latest run of PCT in https://ci.jenkins.io/job/Tools/job/bom/job/PR-1384/4/ failed with

```
[ERROR] Plugin org.jenkins-ci.tools:maven-hpi-plugin:3.33 or one of its dependencies could not be resolved: org.jenkins-ci.tools:maven-hpi-plugin:jar:3.33 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.jenkins-ci.tools:maven-hpi-plugin:3.33 or one of its dependencies could not be resolved: org.jenkins-ci.tools:maven-hpi-plugin:jar:3.33 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
    at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:144)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor (DefaultMavenPluginManager.java:182)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor (DefaultMavenPluginManager.java:286)
    at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor (DefaultBuildPluginManager.java:244)
    at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.getMojoDescriptor (MojoDescriptorCreator.java:239)
    at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments (DefaultLifecycleTaskSegmentCalculator.java:104)
    at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments (DefaultLifecycleTaskSegmentCalculator.java:83)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:89)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

I could reproduce this locally with

```
mvn -Denforcer.skip=true -Dhpi-plugin.version=3.33 -Djenkins.version=2.363 -Dtypes=failsafe,surefire hpi:resolve-test-dependencies hpi:test-hpl surefire:test failsafe:integration-test failsafe:integration-test
```

With this PR I can no longer reproduce the problem as described above.

CC @uhafner

### CODE REVIEW

**Comment by basil** [comment]
Amends #1327. Would like a release if possible please for PCT. Sorry for missing this earlier, I believe I had already fixed this a few days ago but had done it in the wrong repository / checkout and forgot to include the fix as part of #1327. :disappointed:

**Review by jglick — APPROVED** [review]
Should the root module also declare `<repositories>`?

**Comment by basil** [comment]
> Should the root module also declare `<repositories>`?

I do not see why it should.

**Review by uhafner — APPROVED** [review]

**Comment by uhafner** [comment]
https://github.com/jenkinsci/warnings-ng-plugin/releases/tag/v9.18.0

**Pull request merged**
