### PR TITLE
Replace YUI button class with Jenkins default button class for reset reference build action

### PR DESCRIPTION
**Pull request by scherler**
### Testing done
before
Bildschirmfoto 2024-12-21 um 23 32 34

after
Bildschirmfoto 2024-12-21 um 23 47 03

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by uhafner** [comment]
There is no need to make it look as before. It makes more sense to use the default Jenkins styling as secondary button. 

Can change the screenshot so that the button is shown in the correct context? Then I can see if it still looks fine in the use case?

**Comment by Amankkc** [comment]
> @scherler Please try to add some border to enhance the "RESET" Button effect and making it look close to the existing one.

lets drop this as suggested .

**Comment by scherler** [comment]
@uhafner is there a way to get a `result` easily? I am looking ATM to generate a `real` context since the screen shot is taken from me moving the code to somewhere easily reachable

**Comment by uhafner** [comment]
> @uhafner is there a way to get a `result` easily? I am looking ATM to generate a `real` context since the screen shot is taken from me moving the code to somewhere easily reachable

Ah, this is a fake screen shot. I'll deploy the PR into my instance and see how it looks like. One of my example jobs is using these buttons, so this will be faster if I add the screenshot on my own...

**Comment by scherler** [comment]
@uhafner thank you very much!

**Review by uhafner — APPROVED** [review]

**Pull request merged**
