### PR TITLE
Abstracted descriptor matching.

### PR DESCRIPTION
**Pull request by michibat01**
This will permit to have different id's for two different recordIssue preserving the correct Descriptor (Icon, DetailsTableModel, DisplayName).
To do that it is enough to override the "describes" method in the class extending ReportScanningTool,
e.g.: 
@Override
public boolean describes(String id){
    return id.startsWith("my-scanning-tool");
}

### CODE REVIEW

**Comment by uhafner** [comment]
That would imply that you need a prefix for the new IDs. And we would need to override that method at multiple places. Wouldn't it be much simpler if we would additionally store the original tool ID side by side and then use it as fallback if the label descriptor with the new ID is empty?

**Comment by abramobagnara** [comment]
If we will store the original tool ID what would be the point to search descriptor using also the custom ID? Isn't it perfectly pointless?

**Comment by uhafner** [comment]
Hmm, I'm not sure if I understand your point. Maybe it would be helpful if you can create a small integration tests that shows the problem. You can take one of the tests here as a template: https://github.com/jenkinsci/warnings-ng-plugin/blob/master/plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java#L462
This is required for pull requests anyway. 

From your description I expected that you want something like 
```
recordIssues id: "one" tool: javaDoc(pattern:'**/*issues.txt', reportEncoding:'UTF-8')
recordIssues id: "two" tool: javaDoc(pattern:'**/*issues.txt', reportEncoding:'UTF-8')
```

That should show up with 2 URLs `one` and `two` and the Java icon of the id `javaDoc` and the name "JavaDoc"?
This could be achieved if I store in the individual results the id `one` and the original id `javadoc`. 

But maybe I misunderstand your plan? Should the pull request above already show the results without any additional work for `RecordScanningTool` classes?

**Comment by michibat01** [comment]
> That would imply that you need a prefix for the new IDs. And we would need to override that method at multiple places. Wouldn't it be much simpler if we would additionally store the original tool ID side by side and then use it as fallback if the label descriptor with the new ID is empty?

``` 
    public StaticAnalysisLabelProvider create(final String toolId, final String id, @CheckForNull final String name) {
        DescriptorExtensionList<Tool, ToolDescriptor> extensions = jenkins.getDescriptorsFor(Tool.class);
        for (ToolDescriptor descriptor : extensions) {
            if (descriptor.getId().equals(id)) {
                return createNamedLabelProvider(descriptor.getLabelProvider(), name);
            }
        }
        for (ToolDescriptor descriptor : extensions) {
            if (descriptor.getId().equals(toolId)) {
                return createNamedLabelProvider(descriptor.getLabelProvider(), name);
            }
        }

        List<StaticAnalysisToolFactory> factories = jenkins.getExtensionsFor(StaticAnalysisToolFactory.class);
        for (StaticAnalysisToolFactory factory : factories) {
            Optional<StaticAnalysisLabelProvider> labelProvider = factory.getLabelProvider(id);
            if (labelProvider.isPresent()) {
                return createNamedLabelProvider(labelProvider.get(), name);
            }
        }

        return new StaticAnalysisLabelProvider(id, name);
    }
```

Is this what you mean with the above message?
This means to have to propagate the extra argument through all the callers chains.
I've also found some place where this cannot be done: e.g.
```
    public PropertyStatistics getDetails(final String propertyName) {
        Function<String, String> propertyFormatter;
        if ("fileName".equals(propertyName)) {
            propertyFormatter = new BaseNameMapper();
        }
        else if ("origin".equals(propertyName)) {
            propertyFormatter = origin -> new LabelProviderFactory().create(origin,
                    getIssues().getNameOfOrigin(origin)).getName();
        }
        else {
            propertyFormatter = Function.identity();
        }
        return new PropertyStatistics(report, newIssues, propertyName, propertyFormatter);
    }
```
My original proposal is far less invasive and permits to associate arbitrary (and possibly different) LabelProvider according to policies defined by Tool.
Once said that I'm willing to follow your guidelines about the approach you feel better to solve the original issue (that is exactly what you describe in your last message)

**Comment by michibat01** [comment]
As Abramo wrote above, another possibility is to use **always** the toolId to create StaticAnalysisLabelProvider,
but I fear that this might create problems with StaticAnalysisToolFactory

**Comment by uhafner** [comment]
Are you planning to add a small test that shows the new functionality?

**Comment by michibat01** [comment]
> Are you planning to add a small test that shows the new functionality?

Yes I will.
I am currently busy with something else, but as soon as I have some free time I work there

**Comment by michibat01** [comment]
I added the test.
Note that i have changed the default describes method to do matching with prefix.
Another possibility is that default matching is done by equality and that only interested ReportScanningTool override the describes method to allow for more matches.

**Comment by michibat01** [comment]
@uhafner 
Are we ready to merge now?

**Comment by uhafner** [comment]
I did not find the time yet to check if that does not break anything else. Did you check what happens if we have two parser IDs that share the same prefix? (Or where one parser ID is prefix of another one?)

Otherwise the PR looks fine!

**Comment by michibat01** [comment]
@uhafner 
Did you have time to look at the changes? how do you want to proceed?

**Comment by uhafner** [comment]
> @uhafner
> Did you have time to look at the changes? how do you want to proceed?

As mentioned above, the code looks fine. I just creates a new problem:

> It takes the first one it finds.
> I think it would be better to avoid putting two parser ids with these ids relations.

Currently some parsers already share the same prefix, this cannot be changed without breaking existing jobs: 
https://github.com/jenkinsci/analysis-model/blob/master/SUPPORTED-FORMATS.md

**Comment by uhafner** [comment]
So I am somewhat unsure what to do. I think when I am finished with my current feature implementation (see #889) I will have some more time to dig into that problem.

**Pull request closed without merging**
