### PR TITLE
Make AncestorInPath Object include Multibranch pipelines

### PR DESCRIPTION
**Pull request by meiswjn**
Resolves [JENKINS-68336](https://issues.jenkins.io/browse/JENKINS-68336)
Multibranch Pipelines do not inherit from AbstractProject but from ComputedFolder. The next similar super class of both ComputedFolder and AbstractProject is BuildableItem.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by uhafner — CHANGES_REQUESTED** [review]
Unfortunately this breaks binary compatibility. Would it still work, if you leave the old API methods unchanged and add an additional one?  I'm almost sure that nobody uses these methods but it might be safer.

**Comment by meiswjn** [comment]
Would you be able to elaborate on this issue? Do you mean that downstream implementations may have issues if they override the method?

**Comment by uhafner** [comment]
> Would you be able to elaborate on this issue? Do you mean that downstream implementations may have issues if they override the method?

No, if they call the method. Then we get a runtime exception since the type changed (source code compatibility is still preserved).

**Comment by meiswjn** [comment]
I think I understand: If somebody uses this plugin and did not specify any version (i.e. uses latest), they will get an error due to the changed API. However, if developers version-pin their dependencies, they should not have any issues with this, right?

I do not know if Jelly / Stapler is able to determine which method to use depending on the type, which would be necessary to fix this issue.

**Comment by uhafner** [comment]
> I think I understand: If somebody uses this plugin and did not specify any version (i.e. uses latest), they will get an error due to the changed API. However, if developers version-pin their dependencies, they should not have any issues with this, right? As soon as they re-compile their plugin, the issue will be gone.

It is only a runtime problem in the Jenkins instance. If another plugin (that is compiled against an older version) is calling the methods then it will break (it is not very probable though since these methods are public only for the framework).

And you are right: recompiling and deploying will help.
 
> I do not know if Jelly / Stapler is able to determine which method to use depending on the type, which would be necessary to fix this issue. Do you have any other idea?

I think Stapler will find the best matching method.

So:

```
    @POST
     public FormValidation doCheckReportEncoding(@AncestorInPath final BuildableItem project,
             @QueryParameter final String reportEncoding) {
         if (!JENKINS.hasPermission(Item.CONFIGURE, project)) {
             return FormValidation.ok();
        }
        return new CharsetValidation().validateCharset(reportEncoding);
    }

```

should be changed to:

```
    @POST
     public FormValidation doCheckReportEncoding(@AncestorInPath final AbstractProject<?, ?> project,
             @QueryParameter final String reportEncoding) {
        return ((BuildableItem) project, reportEncoding);
    }

    @POST
     public FormValidation doCheckReportEncoding(@AncestorInPath final BuildableItem project,
             @QueryParameter final String reportEncoding) {
         if (!JENKINS.hasPermission(Item.CONFIGURE, project)) {
             return FormValidation.ok();
        }
        return new CharsetValidation().validateCharset(reportEncoding);
    }

```

**Comment by meiswjn** [comment]
I am not sure if Stapler is able to handle two methods named the same, as that translates into paths I guess. Unless I did something wrong?

> 15:32:02  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project warnings-ng: Compilation failure
15:32:02  [ERROR] error: javax.annotation.processing.FilerException: Attempt to reopen a file for path C:\Jenkins\workspace\ugins_warnings-ng-plugin_PR-1339\plugin\target\classes\io\jenkins\plugins\analysis\core\steps\AnalysisStepDescriptor\doCheckReportEncoding.stapler

**Comment by uhafner** [comment]
Ok, then this is not possible. Sorry for the extra work I caused. Then we should stay with your initial approach as it is unlikely that someone has problems with the new API signature. 

In order to get the build passing you need to add some ignores for the changed methods, example is here: https://github.com/jenkinsci/warnings-ng-plugin/blob/master/plugin/pom.xml#L603

**Comment by meiswjn** [comment]
> Does it work if you remove the `@POST` `@AncestorInPath` `@QueryParameter` annotations from the method that takes `AbstractProject`? I think the method would then still be available for calls from Java in other plugins, but Stapler would use the other one. (And if those annotations trigger any build-time security checks, then those checks apply to the method in which the implementation is.)

Sadly no, then other architecture tests fail:
> [ERROR] Failures: 
[ERROR]   Architecture Violation [Priority: MEDIUM] - Rule 'methods that are declared in classes that are assignable to hudson.model.Descriptor and have name matching 'doFill[A-Z].*' and have raw return type raw return type of any o
f [class hudson.util.ComboBoxModel, class hudson.util.ListBoxModel] should be annotated with @POST and should be public and should should have a permission check' was violated (8 times):

**Review by uhafner — APPROVED** [review]

**Pull request merged**
