### PR TITLE
discoverGitReferenceBuild => discoverReferenceBuild

### PR DESCRIPTION
**Pull request by SunBlack**
We are still using `referenceJobName` as parameter to `recordIssues`, as the documentation doesn't really say, what the benefit of the new option is.

Therefore I tried it now, if I see myself some differences (until now I see no differences, so no idea why I should use it), but the suggested new variant doesn't work, as I'm getting:
```
java.lang.NoSuchMethodError: No such DSL method 'discoverGitReferenceBuild' found among steps
```
So I checked if I really have the `Forensics API Plugin` installed (yes: 1.15.1) and after this used the `Pipeline Syntax` tool and this suggested:
```
discoverReferenceBuild referenceJob: 'myRefJob'
```

And it seems correct, when comparing the GitHub search results ([`discoverReferenceBuild`](https://github.com/jenkinsci/forensics-api-plugin/search?q=discoverReferenceBuild) vs. [`discoverGitReferenceBuild`](https://github.com/jenkinsci/forensics-api-plugin/search?q=discoverGitReferenceBuild))

### CODE REVIEW

**Comment by uhafner** [comment]
The `discoverGitReferenceBuild` step is available as well, this is the only implementation that creates non-trivial results. This step requires the installation of the [git-forensics](https://github.com/jenkinsci/git-forensics-plugin) plugin. Example output: https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/view/change-requests/job/PR-1393/3/. 

The `discoverReferenceBuild` step simply does the same thing as the warnings plugin provides on its own.

**Comment by SunBlack** [comment]
> The `discoverGitReferenceBuild` step is available as well, this is the only implementation that creates non-trivial results.

Ah, that explains why I first found `discoverGitReferenceBuild` and not `discoverReferenceBuild` via the GitHub search, which confused me since our Jenkins instance didn't know the Git variant, and while writing this MR description, I found the GitHub search revealed the exact opposite.

> The `discoverReferenceBuild` step simply does the same thing as the warnings plugin provides on its own.

In this case, I think it would make sense to expand the documentation. Currently it mentions that the base plugin is available, but not what advantages it has to use the Git-specific variant when using a fixed reference build, and there is no sample code either. Since the base plugin is installed automatically, I think that would make sense.

Just from my experiments now:
- Using the legacy style you are getting: 
image
- Using `discoverReferenceBuild` hides the warning, but reference build is reported twice
image
- Using `discoverGitReferenceBuild` somehow doesn't work for us, as it seems you need to call `discoverReferenceBuild` as well ine the baseline job (?), which is not mentioned in the documentation, as I get:
  ```
  Configured reference job: 'doc'
  -> selected build '#226' of reference job does not yet contain a `GitCommitsRecord`
  -> no reference build found
  No reference build found that contains matching commits
  ```
  
  And `GitCommitsRecord` seems not to be a valid command.


As far as I read it now, the `Git Forensics Jenkins Plugin` actually only makes sense if you need a repository evaluation, if the evaluation from your Git hoster (GitHub, GitLab, Bitbucket, ...) is not enough, or you do not have a reference job. The advantage of the separate plugin seems to be that the reference build analysis would have to be done only once, if you call the plugin here several times.  For the last point, though, it would also be interesting if there is a list somewhere of which known plugins all benefit from this.

**Comment by uhafner** [comment]
> > The `discoverReferenceBuild` step simply does the same thing as the warnings plugin provides on its own.
> 
> In this case, I think it would make sense to expand the documentation. Currently it mentions that the base plugin is available, but not what advantages it has to use the Git-specific variant when using a fixed reference build, and there is no sample code either. Since the base plugin is installed automatically, I think that would make sense.

Yes, my plan was to remove all the warnings plugin parts (code and documentation) and only refer to https://github.com/jenkinsci/git-forensics-plugin#reference-build
The old option is only available because I don't want to break existing configurations.

> 
> Just from my experiments now:
> 
> * Using the legacy style you are getting:
>   image
> * Using `discoverReferenceBuild` hides the warning, but reference build is reported twice

Yes, each plugin that uses the reference build shows it in its summary. This is intentional but can be changed if it helps. 

>   image
> * Using `discoverGitReferenceBuild` somehow doesn't work for us, as it seems you need to call `discoverReferenceBuild` as well ine the baseline job (?), which is not mentioned in the documentation, as I get:
>   ```
>   Configured reference job: 'doc'
>   -> selected build '#226' of reference job does not yet contain a `GitCommitsRecord`
>   -> no reference build found
>   No reference build found that contains matching commits
>   ```
>   

The `GitCommitsRecord` entry will be automatically collected so you normally do not need to do something in your main (reference) job. Maybe the problem was that you started a PR build before a master build with the newly installed git-forensics plugin. As soon as there is a new reference build the commits to compare to are automatically collected. 

> 
> As far as I read it now, the `Git Forensics Jenkins Plugin` actually only makes sense if you need a repository evaluation, if the evaluation from your Git hoster (GitHub, GitLab, Bitbucket, ...) is not enough, or you do not have a reference job. 

It does make sense as soon as you are running builds with Git.

> The advantage of the separate plugin seems to be that the reference build analysis would have to be done only once, if you call the plugin here several times. For the last point, though, it would also be interesting if there is a list somewhere of which known plugins all benefit from this.

Currently only the warnings plugin and coverage plugin are using it.

**Comment by SunBlack** [comment]
> > Just from my experiments now:
> > 
> > * Using the legacy style you are getting:
> >   image
> > * Using `discoverReferenceBuild` hides the warning, but reference build is reported twice
> 
> Yes, each plugin that uses the reference build shows it in its summary. This is intentional but can be changed if it helps.

Depends if the plugin ever makes issues that you don't already have. In general, I prefer not to display redundant information to the user, so it would indeed be nice if you could disable the output or not have it come up at all.

> The `GitCommitsRecord` entry will be automatically collected so you normally do not need to do something in your main (reference) job. Maybe the problem was that you started a PR build before a master build with the newly installed git-forensics plugin. As soon as there is a new reference build the commits to compare to are automatically collected.

Indeed, now it works. Maybe the error message could be improved. Not sure if you can read the information when the job was build and when the plugin was installed, but maybe the message could be adjusted to:
```
"-> selected build '%s' of reference job does not yet contain a `GitCommitsRecord`". If the plugin has been newly installed, you may need to rebuild the reference job.
```
 
> > As far as I read it now, the `Git Forensics Jenkins Plugin` actually only makes sense if you need a repository evaluation, if the evaluation from your Git hoster (GitHub, GitLab, Bitbucket, ...) is not enough, or you do not have a reference job.
> 
> It does make sense as soon as you are running builds with Git.

Which are the benefits? The output with the Git Forensic tool seems to be sill the same as the Non-Git Forensic tool, except that in the log you see the reference short sha. As our CI always merges the source branch in the main branch before building, it should be always the last reference build, so I don't know where the Git variant has any benefits.
 
> > The advantage of the separate plugin seems to be that the reference build analysis would have to be done only once, if you call the plugin here several times. For the last point, though, it would also be interesting if there is a list somewhere of which known plugins all benefit from this.
> 
> Currently only the warnings plugin and coverage plugin are using it.

Good to know, than the information in the readme of the Git Forensic tool is misleading:
```
Several plugins that report build statistics (test results, code coverage, metrics, static analysis warnings)
```
I searched yesterday a while, if there any test plugin (`xunit`, `junit`, ...) is basing on the forensic plugin.

**Pull request closed without merging**
